// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHmck2oWLmgFIw7lhPz_kNnNmpLcdS2CE',
    appId: '1:1621209385:web:d6665dae0fd788d97ec738',
    messagingSenderId: '1621209385',
    projectId: 'flutter-01-faf14',
    authDomain: 'flutter-01-faf14.firebaseapp.com',
    storageBucket: 'flutter-01-faf14.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0t4i9_gEJyGSWxej3pGp44JBV8-ceaWk',
    appId: '1:1621209385:android:070ab6d3795501757ec738',
    messagingSenderId: '1621209385',
    projectId: 'flutter-01-faf14',
    storageBucket: 'flutter-01-faf14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiwVyx-zGbcWn_UsaLYY0FRGBPQqTHwhE',
    appId: '1:1621209385:ios:7bf864346f9e10947ec738',
    messagingSenderId: '1621209385',
    projectId: 'flutter-01-faf14',
    storageBucket: 'flutter-01-faf14.firebasestorage.app',
    iosBundleId: 'com.example.lesson03Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiwVyx-zGbcWn_UsaLYY0FRGBPQqTHwhE',
    appId: '1:1621209385:ios:7bf864346f9e10947ec738',
    messagingSenderId: '1621209385',
    projectId: 'flutter-01-faf14',
    storageBucket: 'flutter-01-faf14.firebasestorage.app',
    iosBundleId: 'com.example.lesson03Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHmck2oWLmgFIw7lhPz_kNnNmpLcdS2CE',
    appId: '1:1621209385:web:39ac500fd4d683687ec738',
    messagingSenderId: '1621209385',
    projectId: 'flutter-01-faf14',
    authDomain: 'flutter-01-faf14.firebaseapp.com',
    storageBucket: 'flutter-01-faf14.firebasestorage.app',
  );
}
